spring:
  datasource:
    driverClassName: "com.mysql.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/workshop"
    username: "testowy"
    password: "qwerty"
  jpa:
    database: "MYSQL"
    show-sql: "true"

security.user.password: "dupa"